### ISSUE TITLE
Site changes

### ISSUE THREAD

**Issue by abb3v** [MostlyHarmlessCafe/Mostly-Harmless-Cafe#25]
The structure of this site needs to be changed. Perhaps not the styling but how the hugo back end works. I've noticed things that could be better. So far I've realized that the `contents` dir contains "tags" and under `contents/posts` are recipes themselves. But for some reason the type of "tags" is `recipe-page`, you need to show a distinction so you can dynamically allocate space for the tags on the index page by checking app pages that have a type of "tag'.

I'm going to rewrite this project since it doesn't follow conventions of how Hugo is meant to work, I'll commit these soon.

**Comment by deadbody13** [comment]
That sounds good. I'll probably spend a day or two looking over it all to try and understand it but I look forward to seeing those changes.
