### ISSUE TITLE
Recipe: Basic Pan Sauce

### ISSUE THREAD

**Issue by breadsmyth** [MostlyHarmlessCafe/Mostly-Harmless-Cafe#4]
Ingredients:

steak (or any meat)
1 shallot, diced
1/2 cup wine
1 cup stock
1 Tbsp cold butter
salt and pepper to taste 

Directions:

1. Cook the meat to your level of doneness. Remove from the pan, and set it on a cutting board. Tent with foil and allow to rest for 15 minutes. 
2. Meanwhile, make the sauce. Pour out cooking oil from the pan until there is just enough to cook the shallot. Sauté the shallot until softened.
3. Add wine and heat on medium-high while scraping the bottom of the pan with a wooden spoon until reduced, about 1-2 minutes. 
4. Add stock and cook on medium-low until the sauce reduces and thickens, about 5-6 minutes.
5. Turn off the heat, and add cold butter to the pan. Continually whisk the butter into the sauce until it disappears.
6. Add any accumulated juices from the steak as it rested, season to taste with salt and pepper, and serve immediately.
Optional: you may strain the sauce to obtain a more uniform texture, though it is not necessary.

Notes:

- This sauce is incredibly versatile and can be adjusted into one of many named sauces by modifying the ingredients.
- Any aromatic vegetables (onion, garlic, celery, etc.) can be substituted or combined in place of the shallot.
- A mild vinegar or more stock can be used in place of wine, and water can be used in place of stock (although, of course, stock is much more flavorful).
- 1/4 cup of cream can be mixed in after the sauce thickens in step 4. This creates an extremely rich and dense sauce, with a brighter color.
- Any acid or chopped fresh herbs can be added just after whisking in the butter to brighten up the sauce. 
- Step 6 is not optional. If you skip this step, Chef John will not be your friend.

**Comment by deadbody13** [comment]
[Submitted](https://cookbook.mostlyharmless.cafe/posts/steak-sauce_breadsmyth.html). Thanks breadsmyth.
